### PR TITLE
Fix bug of the trackState at the barrel instead of the ECal

### LINKED ISSUE #20: Track state at the ECal sometimes appears to be flipped
Sometimes trackState at the ECal appears to be flipped.

Here is an example, where cyan Marker on the left-bottom shows the position of the extrapolated TrackState at the Ecal, which is wrong with respect to the track and cluster position.
prop_flip

### PR DESCRIPTION
**Pull request by dudarboh**
BEGINRELEASENOTES

- Now checking for the intersection with the endcaps even if intersection with the barrel has been found. The closest track state to the last tracker hit is saved

ENDRELEASENOTES

This fixes #20 .

Small cross check shows that tracks with the distance between trackStateAtEcal and closest Ecal hit > 5 m vanish.
And pfo by pfo difference is 0 for all the other tracks, which means they are unaffected.

 

Code feels very clumsy and probably can be improved...
@gaede , @tmadlener will be happy for any thoughts, comments, suggestions..

### CODE REVIEW

File: src/MarlinTrkUtils.cc [hunk 1]
```diff
@@ -821,19 +823,48 @@ namespace MarlinTrk {
...
         encoder[lcio::LCTrackerCellID::side()] = lcio::ILDDetID::bwd;
-      }
-      return_error = marlintrk->propagateToLayer(encoder.lowWord(), trkhit, *trkStateCalo, chi2, ndf, detElementID, IMarlinTrack::modeForward ) ;
+    }
+    return_error_endcap = marlintrk->propagateToLayer(encoder.lowWord(), trkhit, tsEndcap, chi2, ndf, detElementID, IMarlinTrack::modeForward ) ;
+
+    // check which is the right intersection / closer to the trkhit
+    if ( return_error_barrel == IMarlinTrack::no_intersection ){
+        //if barrel fails just return ts at the Endcap if exists
+        return_error = marlintrk->propagateToLayer(encoder.lowWord(), trkhit, *trkStateCalo, chi2, ndf, detElementID, IMarlinTrack::modeForward );
```
Comment (tmadlener) [inline src/MarlinTrkUtils.cc:845]: I think you could save one extrapolation/propagation here, since you have just done it, and you could just use the results from that, right?
```suggestion
        return_error = return_error_endcap;
        *trkStateCalo = tsEndcap;
```

File: src/MarlinTrkUtils.cc [hunk 2]
```diff
@@ -821,19 +823,48 @@ namespace MarlinTrk {
...
+    }
+    else if( return_error_endcap == IMarlinTrack::no_intersection ){
+        //if barrel succeeded and endcap fails return ts at the barrel
+        encoder[lcio::LCTrackerCellID::subdet()] = ecal_barrel_face_ID ;
+        encoder[lcio::LCTrackerCellID::side()]   = lcio::ILDDetID::barrel;
+        return_error = marlintrk->propagateToLayer(encoder.lowWord(), trkhit, *trkStateCalo, chi2, ndf, detElementID, IMarlinTrack::modeForward ) ;
```
Comment (tmadlener) [inline src/MarlinTrkUtils.cc:851]: Similar here
```suggestion
        return_error = return_error_barrel;
        *trkStateCalo = tsBarrel;
```

File: src/MarlinTrkUtils.cc [hunk 3]
```diff
@@ -821,19 +823,48 @@ namespace MarlinTrk {
...
+        double dToBarrel = (hitPos-barrelPos).r();
+        double dToendcap = (hitPos-endcapPos).r();
+        if ( dToBarrel < dToendcap ){
+            encoder[lcio::LCTrackerCellID::subdet()] = ecal_barrel_face_ID ;
+            encoder[lcio::LCTrackerCellID::side()]   = lcio::ILDDetID::barrel;
+            return_error = marlintrk->propagateToLayer(encoder.lowWord(), trkhit, *trkStateCalo, chi2, ndf, detElementID, IMarlinTrack::modeForward ) ;
+        }
+        else{
+            return_error = marlintrk->propagateToLayer(encoder.lowWord(), trkhit, *trkStateCalo, chi2, ndf, detElementID, IMarlinTrack::modeForward );
+        }
```
Comment (tmadlener) [inline src/MarlinTrkUtils.cc:867]: And also here, you could re-use the results that you already have, instead of doing the propagation
```suggestion
        if ( dToBarrel < dToendcap ){
            return_error = return_error_barrel;
            *trkStateCalo = tsBarrel;
        } else {
            return_error = return_error_endcap;
            *trkStateCalo = tsEndcap;
        }
```

**Review by tmadlener — COMMENTED** [review]
I am not entirely sure if my proposal works, but I think you could save a bit of juggling with the `encoder` bitfield and running the propagation multiple times if you re-use the results that you get from the two propgations to the barrel and the endcap that you have to do in any case. Or am I missing something?

**Comment by tmadlener** [comment]
Could you rebase this onto the latest master, so that we pick up the github actions CI workflows?

**Review by tmadlener — APPROVED** [review]
Thanks. Looks good to me. Unless @gaede has more comments, I would merge this.

**Comment by gaede** [comment]
Thanks for this fix !
